# Generated by Django 4.2.8 on 2026-06-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
