# Generated by Django 4.2.8 on 2026-03-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "encrypted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="encrypted/%Y/%m/%d/"
                    ),
                ),
                ("file_size", models.BigIntegerField()),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("public", "Public - Anyone can see"),
                            ("private", "Private - Only owner"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("is_encrypted", models.BooleanField(default=True)),
                ("encryption_key", models.CharField(blank=True, max_length=500)),
                ("downloads", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("download_size", models.BigIntegerField()),
                (
                    "downloaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_records",
                        to="files.fileupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["user", "scope"], name="files_fileu_user_id_17b938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["created_at"], name="files_fileu_created_db90f6_idx"
            ),
        ),
    ]
