# Generated by Django 4.2.8 on 2026-03-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="USBActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("usb_storage", "USB Storage Device"),
                            ("usb_phone", "USB Mobile Device"),
                            ("usb_other", "Other USB Device"),
                        ],
                        default="usb_storage",
                        max_length=50,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("device_path", models.CharField(blank=True, max_length=500)),
                ("captured_image", models.ImageField(upload_to="usb_logs/%Y/%m/%d/")),
                ("image_quality", models.CharField(default="medium", max_length=20)),
                (
                    "image_size",
                    models.IntegerField(default=0, help_text="Size in bytes"),
                ),
                ("system_info", models.JSONField(blank=True, default=dict)),
                ("additional_info", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "connection_duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usb_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("user_action", "User Action"),
                            ("file_operation", "File Operation"),
                            ("security_event", "Security Event"),
                            ("system_event", "System Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("usb_multiple", "Multiple USB Devices"),
                            ("unknown_device", "Unknown Device"),
                            ("high_frequency", "High Frequency Access"),
                            ("unauthorized_access", "Unauthorized Access Attempt"),
                            ("file_access_abnormal", "Abnormal File Access"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "usb_log",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="security_logs.usbactivitylog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usbactivitylog",
            index=models.Index(
                fields=["user", "timestamp"], name="security_lo_user_id_4c53b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usbactivitylog",
            index=models.Index(
                fields=["is_suspicious"], name="security_lo_is_susp_3b571f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usbactivitylog",
            index=models.Index(
                fields=["timestamp"], name="security_lo_timesta_9c5cee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["log_type", "timestamp"], name="security_lo_log_typ_26c927_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["user", "timestamp"], name="security_lo_user_id_ff8a8c_idx"
            ),
        ),
    ]
