# Generated by Django 4.2.8 on 2026-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usbactivitylog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "USB Activity Log",
                "verbose_name_plural": "USB Activity Logs",
            },
        ),
        migrations.RemoveIndex(
            model_name="usbactivitylog",
            name="security_lo_is_susp_3b571f_idx",
        ),
        migrations.RemoveField(
            model_name="usbactivitylog",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="usbactivitylog",
            name="captured_image",
        ),
        migrations.RemoveField(
            model_name="usbactivitylog",
            name="image_quality",
        ),
        migrations.RemoveField(
            model_name="usbactivitylog",
            name="image_size",
        ),
        migrations.RemoveField(
            model_name="usbactivitylog",
            name="is_suspicious",
        ),
        migrations.RemoveField(
            model_name="usbactivitylog",
            name="risk_level",
        ),
        migrations.AddField(
            model_name="usbactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USB_INSERTED", "USB Device Inserted"),
                    ("USB_REMOVED", "USB Device Removed"),
                    ("USB_ACCESSED", "USB Device Accessed"),
                ],
                default="USB_INSERTED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="usbactivitylog",
            name="hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="usbactivitylog",
            name="system_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="usbactivitylog",
            name="device_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="usbactivitylog",
            name="device_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="usbactivitylog",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("usb_storage", "USB Storage Device"),
                    ("usb_phone", "USB Mobile Device"),
                    ("usb_other", "Other USB Device"),
                    ("unknown", "Unknown Device"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="usbactivitylog",
            index=models.Index(
                fields=["device_id"], name="security_lo_device__233f93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usbactivitylog",
            index=models.Index(fields=["action"], name="security_lo_action_5be11a_idx"),
        ),
    ]
