# Generated by Django 4.2.8 on 2026-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_logs", "0002_alter_usbactivitylog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usbactivitylog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="usb_captures/"),
        ),
    ]
