# Generated by Django 4.2.8 on 2026-03-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_logs", "0003_usbactivitylog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usbactivitylog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="usbactivitylog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="usb_logs/"),
        ),
    ]
